### ISSUE TITLE
very minor design checklist

### ISSUE THREAD

**Issue by mcfrank** [langcog/childes-db-website#4]
- [x] Childes DB title at top of page should be pushed further left or visualizations could scoot to center, so they line up better
- [x] font sizes on tabs for API and visualizations could be a bit bigger
- [x] consistent capitalization of childes-db (lowercase), e.g. on API tutorial 
- [x] can unquote/unitalicize text on about page (and put yourself as lead, in first position, @amsan7)
- [x] unitalicize text on homepage (for readibility)

**Comment by mikabr** [comment]
- [x] add some padding between the two rows of "meet the team" boxes
- [x] uncapitalize the "t" in "Team"
- [x] make references to `childesr` (and `childes-db`?) in monospace font

these are me being picky, feel free to ignore if this level of pickiness isn't useful
